on:
  push:
    branches:
      - main
name: ðŸš€ Deploy API to production on push to production branch
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer, npm

      - name: Set Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # server: "ftp.rosymaxpharmacy.com"
          # username: "ECC@affliate.rosymaxpharmacy.com"
          # password: "dLL9DKGiL0Op"
          server: "ftp.rosymaxpharmacy.com"
          username: "cpuser@testing.rosymaxpharmacy.com"
          password: "m6dt{r881Tj="
          local-dir: ./
          server-dir: /
          port: 21
          protocol: ftps
          dangerous-clean-slate: true
